<?php

namespace AppBundle\Repository;

/**
 * BandMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BandMemberRepository extends \Doctrine\ORM\EntityRepository
{
}
