<?php

namespace AppBundle\Repository;

/**
 * CulteInstrumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CulteInstrumentRepository extends \Doctrine\ORM\EntityRepository
{
}
