<?php

namespace AppBundle\Repository;

/**
 * CulteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CulteRepository extends \Doctrine\ORM\EntityRepository
{
}
