<?php

namespace AppBundle\Repository;

/**
 * SecurityGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecurityGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
