<?php

namespace AppBundle\Repository;

/**
 * UploadedFileDesignCulteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UploadedFileDesignCulteRepository extends \Doctrine\ORM\EntityRepository
{
}
