<?php

namespace AppBundle\Repository;

/**
 * UploadedFileCulteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UploadedFileCulteRepository extends \Doctrine\ORM\EntityRepository
{
}
