# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        UserBundle\Entity\User: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        database_provider:
            entity: 
                class: UserBundle:User
                property: email
                
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

            # activate different ways to authenticate
            pattern: ^/
            http_basic: ~
            provider: database_provider

            # activate different ways to authenticate
            pattern: ^/app
            http_basic: ~
            provider: database_provider
            

            # https://symfony.com/doc/current/security/form_login_setup.html
            # form_login: ~

    access_control:
        # require ROLE_USER for /app*
        - { path: ^/app, roles: ROLE_USER }
